[package]
name = "sunrise-libtimezone"
version = "0.1.0"
authors = ["Thog <contact@thog.eu>"]
edition = "2018"

[dependencies]
static_assertions = "0.3"

[dependencies.num-traits]
version = "0.2"
default-features = false
